export const CHANGE_LOGIN = "CHANGE_LOGIN";

export const REQUEST_USER_DATA_PENDING = "REQUEST_USER_DATA_PENDING";

export const REQUEST_USER_DATA_REJECTED = "REQUEST_USER_DATA_REJECTED";

export const REQUEST_USER_DATA_RESOLVED = "REQUEST_USER_DATA_RESOLVED";
